name: gisec
channels:
  - defaults
dependencies:
  - python=3.13
  - pip
  - ninja
  - pip:
      - numpy
      - pytest
      - opencv-python
      - pycocotools
      - scipy==1.15.2
      - PyYAML==6.0.3
      - transformers==4.57.6
      - matplotlib==3.10.7
      - --index-url https://download.pytorch.org/whl/cu130
      - --extra-index-url https://pypi.org/simple
      - torch==2.10.0
      - torchvision==0.25.0
      - torchaudio==2.10.0
